# Generated by Django 5.0.3 on 2024-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='USERID')),
                ('first_name', models.CharField(max_length=50, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=50, verbose_name='LastName')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='UserName')),
                ('email', models.EmailField(max_length=50, verbose_name='EmailID')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
