# Generated by Django 5.0.3 on 2024-03-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareListApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDetails',
            fields=[
                ('shareid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SHAREID')),
                ('dop', models.DateField(auto_now_add=True, verbose_name='DateofPurchase')),
                ('comp_name', models.CharField(max_length=50, verbose_name='CompanyName')),
                ('price', models.IntegerField(max_length=10, verbose_name='Price')),
                ('quantity', models.IntegerField(max_length=10, verbose_name='Quantity')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareListApp.userdetails')),
            ],
        ),
    ]
