# Generated by Django 5.0.3 on 2024-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareListApp', '0002_sharedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedetails',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sharedetails',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
